title: PhpSysInfo
description: "phpSysInfo: a customizable PHP script that displays information about your system nicely"
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
